commit with 5 documents and a folder with 1 file
jcarrillog-psl/protractor-workshop-2017 pull request #1
Opened 2018-12-18 14:29 UTC by jcarrillog-psl

Asking for a PR to continue with the workshop Protractor. Thanks!

2018-12-27 19:33 UTC, germandavid85 requested changes

2018-12-27 19:33 UTC, germandavid85 commented on protractor.config.js
> +	//specs: [ 'test/Google.spec.js'],
remove commented code

2018-12-27 19:43 UTC, jcarrillog-psl commented on protractor.config.js
> +	//specs: [ 'test/Google.spec.js'],
Done!

2018-12-27 19:50 UTC, germandavid85 approved these changes

2018-12-27 19:59 UTC, merged

2019-01-11 18:59 UTC, jcarrillog-psl commented
Branch deleted to omit some confusion with the actual two branches created, one created for OSwin10, the other one created for Unix