Master pom
jcarrillog-psl/protractor-workshop-2017 pull request #13
Opened 2019-02-05 18:05 UTC by jcarrillog-psl

Asking for a PR to continue with the workshop Protractor. Thanks!

2019-02-05 19:18 UTC, sorregom requested changes

2019-02-05 19:18 UTC, sorregom commented on src/page/SignInStep.page.ts
> +    private get signInStep(): ElementFinder {
este método lo puedes dividir en varios, me explico, puedes tener un get que te traiga el campo del username y otro para el pass y otro para el submit, ahi si usar el de signIn llenando el formulario y haciendo click en submit (recuerda suar async await para garantizar que espere a que eso termine)

2019-02-05 19:18 UTC, sorregom commented on src/page/index.ts
> +
tienes una línea demás

2019-02-05 19:59 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +    private get signInStep(): ElementFinder {
Done!

2019-02-05 20:02 UTC, jcarrillog-psl commented on src/page/index.ts
> +
Done!

2019-02-05 23:35 UTC, sorregom requested changes

2019-02-05 23:35 UTC, sorregom commented on src/page/ShippingStep.page.ts
> +      $( '#cgv' ).click();
esta propiedad no es clara, primero estás haciendo un click y luego retorna un elemento, dividelo en 2 o 3 que las propiedades sean sólo para obtener los componentes y si necesitas ejecutar acciones las pones dentro de una fn con async await

2019-02-05 23:35 UTC, sorregom commented on src/page/ShippingStep.page.ts
> +      setTimeout(function(){ },3000);
esto no está haciendo nada, después de 3 segundos se ejecuta la fn dentro del timeout (qu eno hace nada)

2019-02-05 23:35 UTC, sorregom commented on src/page/SignInStep.page.ts
> +    private get signInStep(): ElementFinder {
puedes cambiar el nombre de la fn a submitButton por ejemplo para tener más claridad de que es lo que hace

2019-02-05 23:35 UTC, sorregom commented on src/page/SignInStep.page.ts
> +    public goToSignInStep(): promise.Promise<void> {
este nombre no es claro de lo que hace

2019-02-05 23:35 UTC, sorregom commented on src/page/SignInStep.page.ts
> +    public goToUsernameEmail(): promise.Promise<void> {
este nombre no es claro de lo que hace

2019-02-05 23:35 UTC, sorregom commented on src/page/SignInStep.page.ts
> +     public goToUsernamePass(): promise.Promise<void> {
este nombre no es claro de lo que hace

2019-02-05 23:35 UTC, sorregom commented on src/page/SignOut.page.ts
> +    private get signOut(): ElementFinder {
podrías poner que es un poco más especifico que es un boton o que es

2019-02-05 23:35 UTC, sorregom commented on test/BuyTshirt.spec.ts
> +import { MenuContentPage } from '../src/page' ;
puedes poner todos los import de los pages en un sólo import y no con multiples imports

2019-02-07 16:30 UTC, sorregom commented
agregar constructor con la nueva implementacion para todos los pages

2019-02-20 17:12 UTC, jcarrillog-psl commented on test/BuyTshirt.spec.ts
> +import { MenuContentPage } from '../src/page' ;
Done!

2019-02-21 13:14 UTC, aperdomob requested changes

2019-02-21 13:14 UTC, aperdomob commented on src/page/SignInStep.page.ts
> +  public async goToSubmitButton(): Promise<void> {
deberias tener un metodo unico llamado login que reciba el user y el password y darle clic en login.

No deberían ser metodos por separado. Adicionalmente la idea es que los parametros se pasen por la prueba y no esten quemados en el page object

2019-02-21 15:36 UTC, sorregom requested changes

2019-02-21 15:36 UTC, sorregom commented on src/page/SignInStep.page.ts
> +  public async goToSubmitButton(): Promise<void> {
+1

2019-02-21 15:36 UTC, sorregom commented on src/page/SignOutSession.page.ts
> +import { $, ElementFinder } from 'protractor' ;
el sing out no es necesario para lo que estamos revisando, puedes borrar este page

2019-02-21 15:36 UTC, sorregom commented on test/BuyTshirt.spec.ts
> +        , ProductDetailPage
por lo general se pone la `coma` después del objeto que estás importando así:

import from {
  MenuContentPage,
  ProductDetailPage,
  ...
} from '../src/page';

2019-02-21 15:36 UTC, sorregom commented on test/BuyTshirt.spec.ts
> +        await signOutSessionPage.goToSignOutSession();
esto no es necesario

2019-02-21 19:27 UTC, jcarrillog-psl commented on test/BuyTshirt.spec.ts
> +        , ProductDetailPage
Done!

2019-02-21 19:28 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +  public async goToSubmitButton(): Promise<void> {
Done!

2019-02-21 19:28 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +     public goToUsernamePass(): promise.Promise<void> {
Done!

2019-02-21 19:29 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +    public goToUsernameEmail(): promise.Promise<void> {
done!

2019-02-21 19:29 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +    public goToSignInStep(): promise.Promise<void> {
done!

2019-02-21 19:29 UTC, jcarrillog-psl commented on src/page/ShippingStep.page.ts
> +      setTimeout(function(){ },3000);
Done!

2019-02-21 19:29 UTC, jcarrillog-psl commented on src/page/ShippingStep.page.ts
> +      $( '#cgv' ).click();
Done!

2019-02-21 19:30 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +    private get signInStep(): ElementFinder {
Done!

2019-02-21 19:30 UTC, jcarrillog-psl commented on src/page/SignOut.page.ts
> +    private get signOut(): ElementFinder {
Done!

2019-02-21 20:48 UTC, sorregom requested changes

2019-02-21 20:48 UTC, sorregom commented on src/page/SignInStep.page.ts
> +  public async loginButton(email:string, pass:string): Promise<void> {
procura que el nombre del método sea especifico de lo que hace, al leer este nombre suena más a que es un componente de la página y no un método

2019-02-21 20:48 UTC, sorregom commented on test/BuyTshirt.spec.ts
> +  const signOutSessionPage: SignOutSessionPage = new SignOutSessionPage();
esto no es necesario, puedes borrar el signOut

2019-02-21 20:48 UTC, sorregom commented on test/BuyTshirt.spec.ts
> +    await signOutSessionPage.goToSignOutSession();
borra esto

2019-02-21 20:54 UTC, jcarrillog-psl commented on src/page/SignOutSession.page.ts
> +import { $, ElementFinder } from 'protractor' ;
done!

2019-02-21 20:54 UTC, jcarrillog-psl commented on test/BuyTshirt.spec.ts
> +        await signOutSessionPage.goToSignOutSession();
done!

2019-02-21 20:54 UTC, jcarrillog-psl commented on test/BuyTshirt.spec.ts
> +    await signOutSessionPage.goToSignOutSession();
done!

2019-02-21 20:55 UTC, jcarrillog-psl commented on test/BuyTshirt.spec.ts
> +  const signOutSessionPage: SignOutSessionPage = new SignOutSessionPage();
done!

2019-02-21 21:01 UTC, jcarrillog-psl commented on src/page/SignInStep.page.ts
> +  public async loginButton(email:string, pass:string): Promise<void> {
Done!

2019-03-07 12:34 UTC, aperdomob approved these changes

2019-04-02 14:55 UTC, sorregom approved these changes
LGTM good job man 🥇

2019-04-02 14:56 UTC, merged